export const VENDOR_CATEGORY_OPTIONS = [
  "Air Conditioners & Accessories",
  "Animal Feed & Veterinary Drugs",
  "Audio & Visual Systems",
  "Book Binding & Paper Finishing Materials",
  "Books & Publications",
  "Building & Construction Materials",
  "Cameras & Photography Equipment",
  "Cell Culture & Biological Materials",
  "Cement & Precast Products",
  "CIDA EM1-EM3 Contractors",
  "CIDA Registered Contractors (Bridge)",
  "CIDA Registered Contractors (Building)",
  "CIDA Registered Contractors (Highway)",
  "CIDA Registered Contractors (Water Supply & Drainage)",
  "Computer Hardware & Software",
  "Construction & Maintenance",
  "Curtain Materials & Accessories",
  "Electrical & Electronic Appliances",
  "Electrical Wiring & Fittings",
  "Fertilizers & Agro Chemicals",
  "Fibre Glass & Plastic Products",
  "Fire Safety Equipment",
  "General Hardware & Tools",
  "General Laboratory Chemicals",
  "Kitchen Utensils & Cutlery",
  "Laboratory Chemicals (Specialized)",
  "Laboratory Equipment",
  "Laboratory Glassware & Plasticware",
  "Landscaping",
  "Machinery & Industrial Equipment",
  "Maintenance of Air Conditioners",
  "Medical & Dental Consumables",
  "Medical Equipment",
  "Motor Spare Parts",
  "Office Equipment",
  "Pest Control Service",
  "Photography & Videography",
  "Printing & Binding of Books",
  "Printing & Supply of ID Cards",
  "Rebuilding & Retreading of Tyres",
  "Repair & Maintenance of Computers & Networks",
  "Repair of Electrical Appliances",
  "Repair of Gas Systems",
  "Repair of Laboratory Equipment",
  "Repair of Motor Vehicle",
  "Repair of Motor Cycles",
  "Repair of Office Equipment",
  "Repair of Three Wheelers",
  "Repair of Tractors",
  "Rubber Items, Seals & Stamps",
  "Safety Equipment",
  "Sanitary & Cleaning Items",
  "Sawn Timber & Wood Products",
  "Security Systems",
  "Service & Lubrication of Motor Vehicles",
  "Service & Lubrication of Motorcycles",
  "Service & Lubrication of Three Wheelers",
  "Sports Goods",
  "Stationery & Office Consumables",
  "Steel Furniture",
  "Supply & Operation of Earth Moving Equipment",
  "Teaching & Workshop Equipment",
  "Toner Cartridges & Master Rolls",
  "Transport Services",
  "Tree Removal & Landscaping Services",
  "Tyres & Tubes",
  "Uniform Materials & Accessories",
  "University Ceremony Items",
  "Vehicle & Motorcycle Batteries",
  "Vehicles & Transport Equipment",
  "Wheel Alignment Services",
  "Wooden Furniture",
];
